from __future__ import annotations

import json
import os
from datetime import datetime
from glob import glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # repo root
JOURNAL_DIR = os.path.join(ROOT, "journal")

def read_json(path: str) -> dict | None:
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return None

def fmt_float(x) -> str:
    try:
        return f"{float(x):.6f}"
    except Exception:
        return ""

def build_index(rows: list[dict]) -> str:
    lines = []
    lines.append("# BTC Futures Journal Index")
    lines.append("")
    lines.append("This file is auto-generated by GitHub Actions after each playbook run.")
    lines.append("")
    lines.append("- **Latest:** [LATEST.md](LATEST.md) | [LATEST.json](LATEST.json)")
    lines.append("")
    lines.append("| Date | BTC Spot (USD) | OKX Funding | Next Funding (ms epoch) | File |")
    lines.append("|---|---:|---:|---:|---|")

    for r in rows:
        date = r.get("date", "")
        spot = r.get("btc_spot_usd", "")
        funding = r.get("fundingRate", "")
        nxt = r.get("nextFundingTime", "")

        rel = r.get("relpath", "").replace("\\", "/")
        # index lives in /journal, so link paths should be relative to that folder
        link = rel.split("journal/", 1)[-1] if "journal/" in rel else rel
        lines.append(f"| {date} | {spot} | {funding} | {nxt} | [{os.path.basename(link)}]({link}) |")

    lines.append("")
    return "\n".join(lines)

def build_latest_md(latest: dict, rel_json_path: str) -> str:
    okx = (latest or {}).get("derivatives_okx", {}) or {}
    spot = (latest or {}).get("btc_spot_usd", "")
    ts = (latest or {}).get("run_timestamp_et", "")
    funding = okx.get("fundingRate", "")
    premium = okx.get("premium", "")

    rel_link = rel_json_path.replace("\\", "/")
    rel_link = rel_link.split("journal/", 1)[-1] if "journal/" in rel_link else rel_link

    lines = []
    lines.append("# Latest BTC Futures Playbook")
    lines.append("")
    lines.append(f"- **Run (ET):** {ts}")
    lines.append(f"- **BTC Spot (USD):** {spot}")
    lines.append(f"- **OKX fundingRate:** {funding}")
    lines.append(f"- **OKX premium:** {premium}")
    lines.append("")
    lines.append(f"Source JSON: [{os.path.basename(rel_link)}]({rel_link})")
    lines.append("")
    return "\n".join(lines)

def main() -> None:
    # journal/YYYY/YYYY-MM-DD.json
    files = sorted(glob(os.path.join(JOURNAL_DIR, "*", "*.json")))
    rows = []

    for path in files:
        data = read_json(path)
        if not isinstance(data, dict):
            continue

        base = os.path.basename(path)
        date = base.replace(".json", "")

        okx = data.get("derivatives_okx", {}) or {}
        rows.append({
            "date": date,
            "btc_spot_usd": data.get("btc_spot_usd", ""),
            "fundingRate": fmt_float(okx.get("fundingRate")),
            "nextFundingTime": okx.get("nextFundingTime", ""),
            "path": path,
            "relpath": os.path.relpath(path, ROOT),
        })

    # newest first by date string
    rows.sort(key=lambda r: r["date"], reverse=True)

    # write INDEX.md
    index_path = os.path.join(JOURNAL_DIR, "INDEX.md")
    with open(index_path, "w", encoding="utf-8") as f:
        f.write(build_index(rows[:120]))
        f.write("\n")

    # write LATEST.md + LATEST.json
    if rows:
        newest = rows[0]
        newest_data = read_json(newest["path"]) or {}
        latest_json_path = os.path.join(JOURNAL_DIR, "LATEST.json")
        with open(latest_json_path, "w", encoding="utf-8") as f:
            json.dump(newest_data, f, indent=2, sort_keys=True)
            f.write("\n")

        latest_md_path = os.path.join(JOURNAL_DIR, "LATEST.md")
        with open(latest_md_path, "w", encoding="utf-8") as f:
            f.write(build_latest_md(newest_data, newest["relpath"]))
            f.write("\n")

if __name__ == "__main__":
    main()
